workflow to generate og images (#55)

diff --git a/.github/workflows/build-og.yaml b/.github/workflows/build-og.yaml
--- a/.github/workflows/build-og.yaml
+++ b/.github/workflows/build-og.yaml
@@ -1,14 +1,109 @@
+name: Generate OpenGraph Images
+
 on:
   push:
     tags:
       - og-v*
   workflow_dispatch:
+    inputs:
+      staticParams:
+        description: 'The number of static params to be generated (-1 for all)'
+        required: false
+        default: 10
+        type: number
+
+concurrency:
+  group: 'opengraph-image'
+  cancel-in-progress: true
+
+permissions:
+  contents: write
+  pull-requests: write
+
+env:
+  STATIC_PARAMS: ${{ inputs.staticParams }}
 
 jobs:
-  hello:
-    runs-on: ''
+  build:
+    runs-on: ubuntu-24.04
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+            echo "manager=pnpm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=pnpx" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - uses: pnpm/action-setup@v4
+        name: Install pnpm
+        with:
+          run_install: false
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      # Install Just runner
+      - uses: taiki-e/install-action@just
+      - name: Set Secrets
+        run: | # Secrets needed on the server
+          echo "NEXT_PUBLIC_OUTPUT_EXPORT=${{ vars.NEXT_PUBLIC_OUTPUT_EXPORT }}" >> .env.production
+          echo "NEXT_PUBLIC_IMAGES_UNOPTIMIZED=${{ vars.NEXT_PUBLIC_IMAGES_UNOPTIMIZED }}" >> .env.production
+          echo "NEXT_PUBLIC_STATIC_PARAMS=${{ env.STATIC_PARAMS }}" >> .env.production
+          echo "NEXT_PUBLIC_SECRET=${{ vars.NEXT_PUBLIC_SECRET }}" >> .env.production
+          echo "NEXT_PUBLIC_CACHE_REVALIDATION=${{ vars.NEXT_PUBLIC_CACHE_REVALIDATION }}" >> .env.production
+
+          echo "NEXT_PUBLIC_APP_ENV=${{ vars.NEXT_PUBLIC_APP_ENV }}" >> .env.production
+          echo "NEXT_PUBLIC_GITHUB_REPO=${{ vars.NEXT_PUBLIC_GITHUB_REPO }}" >> .env.production
+          echo "NEXT_PUBLIC_BRAND=${{ vars.NEXT_PUBLIC_BRAND }}" >> .env.production
+          echo "NEXT_PUBLIC_BRAND_SHORT=${{ vars.NEXT_PUBLIC_BRAND_SHORT }}" >> .env.production
+          echo "NEXT_PUBLIC_BRAND_SLOGAN=${{ vars.NEXT_PUBLIC_BRAND_SHORT }}" >> .env.production
+          echo "NEXT_PUBLIC_DOMAIN=${{ vars.NEXT_PUBLIC_BRAND_SHORT }}" >> .env.production
+      - name: Build OpenGraph Images
+        run: just build_opengraph_images
       - run: |
-          echo "Log level: $LEVEL"
-          echo "Tags: $TAGS"
-          echo "Environment: $ENVIRONMENT"
+          echo "Environment: $NEXT_PUBLIC_APP_ENV"
+      - name: Copy OpenGraph Images
+        run: |
+          just copy_opengraph_images
+      - run: |
+          git status
+      - name: Create Pull Request
+        uses: peter-evans/create-pull-request@v7
+        with:
+          commit-message: update opengraph images
+          title: Update OpenGraph Images
+          body: 'Generate open graph images to reflect release changes from ${{ github.ref_type }}: ${{ github.ref_name }} at commit ${{ github.sha }}' 
+          branch: update-og-images
+          base: main
+          add-paths: |
+            public/og/
